name: game_analytics

profile: game_analytics


model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  game_analytics:
    # Staging: views in STAGING schema
    staging:
      +materialized: view
      +schema: staging
    # Marts: tables in MARTS schema (core + analytics)
    marts:
      +materialized: table
      +schema: marts
